# Generated by Django 4.2.2 on 2023-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
